[package]
name = "stepflow-exception"
version = "0.1.0"
edition = "2024"

[dependencies]
stepflow-dto = { path = "../stepflow-dto" }
once_cell = "1.19.0"
serde = { version = "1.0", features = ["derive"] }
