[package]
name = "stepflow-eventbus"
version = "0.1.0"
edition = "2024"

[dependencies]
stepflow-dto = { path = "../stepflow-dto" }
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
thiserror = "1.0"
once_cell = "1.19"
tracing = "0.1"
anyhow = "1.0"