[package]
name = "stepflow-eventbus"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
async-trait.workspace = true
thiserror.workspace = true
once_cell.workspace = true
tracing.workspace = true
anyhow.workspace = true

stepflow-dto = { path = "../stepflow-dto" }